---
dataset:
  # dataset config
  data: "cifar10"
  root: "./data"

model:
  # model config
  device: "cpu"
  n_kernels: 16
  inner_lr: 5e-3
  wd: 5e-5
  lr: 1e-2
  in_channels: 3
  out_dim: 10


strategy:
  _target_: pFedHN.strategy.pFedHN
  # strategy config

client:
  # client config
  num_epochs: 50
  num_rounds: 5000
  num_nodes: 50
  num_nodes_stratergy_client: 13
  batch_size: 64
  num_classes_per_node: 2